all:
  children:
    rseries:
      hosts:
        r5900-a:
          f5_host: 192.0.2.10
          f5_platform_type: rseries

    velos_controllers:
      hosts:
        velos-controller-a:
          f5_host: 192.0.2.20
          f5_platform_type: velos-controller

    velos_partitions:
      hosts:
        velos-partition-edge-a:
          f5_host: 192.0.2.30
          f5_platform_type: velos-partition
